server:
  ssl:
    key-store: cert.p12
    key-store-password: '123456'
    key-store-type: PKCS12 
  port: '8090'
notification:
  mattermost:
    webhook-url: https://meeting.ssafy.com/hooks/4uwa1nkf6id938iw3nxqz8mnta
    pretext: Signal-BackEnd
    enabled: 'true'